# docker-compose.yml

version: '3.7'

services:
    ejercicios:
        build: .
        volumes:
            - ./Ejs:/Ejs
        working_dir: /Ejs

    flask:
        build: .
        depends_on:
            - mongo
        ports:
            - "8080:5000"
        volumes:
            - ./flask:/flask

    mongo:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - ./dump:/dump
            - ./datos_db:/datos/db
