# docker-compose.yml

version: '3.7'

services:
    ejercicios:
        build: .
        volumes:
            - ./Ejs:/Ejs
        working_dir: /Ejs

    flask:
        build:
            context: .
        ports:
            - "8080:5000"
        volumes:
            - ./flask:/flask
        working_dir: /flask
